#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.0.1 on Mon Apr 19 20:29:59 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((615, 564))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 5)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 5)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Fichero: ")
        sizer_5.Add(label_2, 0, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_5.Add(self.text_ctrl_1, 0, 0, 0)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "Abrir Fichero")
        sizer_4.Add(self.button_1, 0, wx.ALL | wx.EXPAND, 5)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Nueva Partida")
        sizer_4.Add(self.button_2, 0, wx.ALL | wx.EXPAND, 5)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_6, 0, wx.ALL | wx.EXPAND, 5)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Nº Filas: ")
        sizer_6.Add(label_3, 0, 0, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_6.Add(self.spin_ctrl_1, 0, 0, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_7, 0, wx.ALL | wx.EXPAND, 5)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Jugada: ")
        sizer_7.Add(label_4, 0, 0, 0)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_7.Add(self.text_ctrl_2, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Lista de Jugadas")
        sizer_4.Add(label_5, 0, wx.ALL | wx.EXPAND, 5)

        self.list_box_1 = wx.ListBox(self.panel_1, wx.ID_ANY, choices=["choice 1"])
        sizer_4.Add(self.list_box_1, 1, wx.ALL | wx.EXPAND, 5)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Puntos= 0", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetMinSize((159, 31))
        sizer_4.Add(label_6, 0, wx.ALL | wx.EXPAND | wx.SHAPED, 10)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_3.Add(self.panel_2, 1, wx.ALL | wx.EXPAND, 10)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Escriba jugada y pulse [ENTER]", style=wx.ALIGN_LEFT)
        sizer_2.Add(label_1, 0, wx.ALL | wx.EXPAND, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class Main(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class Main

if __name__ == "__main__":
    Desliza = Main(0)
    Desliza.MainLoop()
